version: "3"

networks:
  airline-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24

services:
  database:
    image: postgres
    container_name: project_db-compose
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "airline tickets"
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - /home/lucas/Documentos/UFU/ASA/Projeto_Airline_Tickets/pg-data:/var/lib/postgresql/data
      #- ./database_init.sql:/docker-entrypoint-initdb.d/database_init.sql
    networks:
      airline-network:
        ipv4_address: 172.22.0.2

  airline_app:
    image: flask_app:prod 
    container_name: flask_app_prod-compose
    restart: always
    depends_on:
      - database
    ports:
      - 5000:5000
    networks:
      airline-network:
        ipv4_address: 172.22.0.3
